/// <reference types="react" />
import _Import2 from './Libraries/Components/Button';
import _Import3 from './Libraries/Components/CheckBox/CheckBox';
import _Import4 from './Libraries/Components/DatePicker/DatePickerIOS';
import _Import8 from './Libraries/Image/ImageBackground';
import _Import9 from './Libraries/Components/TextInput/InputAccessoryView';
import _Import10 from './Libraries/Components/Keyboard/KeyboardAvoidingView';
import _Import11 from './Libraries/Components/MaskedView/MaskedViewIOS';
import _Import12 from './Libraries/Modal/Modal';
import _Import13 from './Libraries/Components/Picker/Picker';
import _Import14 from './Libraries/Components/Picker/PickerIOS';
import _Import18 from './Libraries/Components/ScrollView/ScrollView';
import _Import22 from './Libraries/Components/Switch/Switch';
import _Import23 from './Libraries/Components/RefreshControl/RefreshControl';
import _Import24 from './Libraries/Components/StatusBar/StatusBar';
import _Import29 from './Libraries/Components/Touchable/TouchableNativeFeedback';
import _Import31 from './Libraries/Components/Touchable/TouchableWithoutFeedback';
import _Import33 from './Libraries/Lists/VirtualizedList';
import _Import36 from './Libraries/Alert/Alert';
import _Import44 from './Libraries/Components/DatePickerAndroid/DatePickerAndroid';
import _Import47 from './Libraries/Utilities/Dimensions';
import _Import48 from './Libraries/Animated/src/Easing';
import _Import57 from './Libraries/EventEmitter/NativeEventEmitter';
import _Import61 from './Libraries/Utilities/PixelRatio';
import _Import62 from './Libraries/PushNotificationIOS/PushNotificationIOS';
import _Import64 from './Libraries/Share/Share';
import _Import70 from './Libraries/Components/AppleTV/TVEventHandler';
import { HostComponent as _HostComponentInternal } from "./Libraries/Renderer/shims/ReactNativeTypes";
export declare type HostComponent<T> = _HostComponentInternal<T>;
declare const _default: {
    readonly AccessibilityInfo: any;
    readonly ActivityIndicator: any;
    readonly Button: _Import2;
    readonly CheckBox: _Import3;
    readonly DatePickerIOS: _Import4;
    readonly DrawerLayoutAndroid: _Import3;
    readonly FlatList: any;
    readonly Image: any;
    readonly ImageBackground: _Import8;
    readonly InputAccessoryView: _Import9;
    readonly KeyboardAvoidingView: _Import10;
    readonly MaskedViewIOS: _Import11;
    readonly Modal: _Import12;
    readonly Picker: _Import13;
    readonly PickerIOS: _Import14;
    readonly ProgressBarAndroid: _Import3;
    readonly ProgressViewIOS: any;
    readonly SafeAreaView: any;
    readonly ScrollView: _Import18;
    readonly SectionList: any;
    readonly SegmentedControlIOS: any;
    readonly Slider: any;
    readonly Switch: _Import22;
    readonly RefreshControl: _Import23;
    readonly StatusBar: _Import24;
    readonly Text: Text;
    readonly TextInput: any;
    readonly Touchable: any;
    readonly TouchableHighlight: any;
    readonly TouchableNativeFeedback: _Import29;
    readonly TouchableOpacity: any;
    readonly TouchableWithoutFeedback: _Import31;
    readonly View: any;
    readonly VirtualizedList: _Import33;
    readonly VirtualizedSectionList: any;
    readonly ActionSheetIOS: any;
    readonly Alert: _Import36;
    readonly Animated: any;
    readonly Appearance: any;
    readonly AppRegistry: any;
    readonly AppState: any;
    readonly AsyncStorage: any;
    readonly BackHandler: any;
    readonly Clipboard: any;
    readonly DatePickerAndroid: _Import44;
    readonly DeviceInfo: any;
    readonly DevSettings: any;
    readonly Dimensions: _Import47;
    readonly Easing: _Import48;
    readonly findNodeHandle: any;
    readonly I18nManager: any;
    readonly ImagePickerIOS: any;
    readonly InteractionManager: any;
    readonly Keyboard: any;
    readonly LayoutAnimation: any;
    readonly Linking: any;
    readonly NativeDialogManagerAndroid: any;
    readonly NativeEventEmitter: _Import57;
    readonly Networking: any;
    readonly PanResponder: any;
    readonly PermissionsAndroid: any;
    readonly PixelRatio: _Import61;
    readonly PushNotificationIOS: _Import62;
    readonly Settings: any;
    readonly Share: _Import64;
    readonly StatusBarIOS: any;
    readonly StyleSheet: any;
    readonly Systrace: any;
    readonly ToastAndroid: any;
    readonly TurboModuleRegistry: any;
    readonly TVEventHandler: _Import70;
    readonly UIManager: any;
    readonly unstable_batchedUpdates: any;
    readonly useColorScheme: any;
    readonly useWindowDimensions: any;
    readonly UTFSequence: any;
    readonly Vibration: any;
    readonly YellowBox: any;
    readonly DeviceEventEmitter: any;
    readonly NativeAppEventEmitter: any;
    readonly NativeModules: any;
    readonly Platform: any;
    readonly processColor: any;
    readonly requireNativeComponent: <T>(uiViewClassName: string) => any;
    readonly unstable_RootTagContext: any;
    readonly unstable_enableLogBox: () => void;
    readonly ColorPropType: any;
    readonly EdgeInsetsPropType: any;
    readonly PointPropType: any;
    readonly ViewPropTypes: any;
};
export default _default;
