yarn run v1.21.1
$ /Users/eloy/Code/ReactNative/react-native/node_modules/.bin/flow-to-ts Libraries/Core/ReactNativeVersion.js
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 * @generated by scripts/bump-oss-version.js
 * @flow
 */

exports.version = {
  major: 0,
  minor: 0,
  patch: 0,
  prerelease: null
};
Done in 0.45s.
